[tool.poetry]
name = "oil-and-rope"
version = "0.0.2"
description = "Oil & Rope is a Django project for managing Roleplay Games."
authors = ["LeCuay <suso.becerra98@gmail.com>"]
license = "MIT"
repository = "https://github.com/oil-rope/oil-and-rope/"

[tool.poetry.dependencies]
python = "^3.9"
Django = "4.0.2"
channels = "^3.0"
channels-redis = "^3.3"
"discord.py" = {extras = ["voice"], version = "^1.7"}
django-allauth = "^0.46"
django-crispy-forms = "^1.13"
django-ckeditor = "^6.2"
django-cors-headers = "^3.10"
# NOTE: Package `django-modeltranslation seems to have a problem with Django 4+
django-modeltranslation = "^0.17"
django-mptt = "^0.13"
django-mptt-admin = "^2.1"
djangorestframework = "^3.12"
django-simple-history = "^3.0"
django-tables2 = "^2.4"
faker = "^9.9"
gunicorn = "^20.1"
Pillow = "^8.4"
psycopg2 = "^2.9"
python-dateutil = "^2.8"
python-dotenv = "^0.19"
requests = "^2.26"
Twisted = {extras = ["tls", "http2"], version = "^21.7"}
xlrd = "^2.0"

[tool.poetry.dev-dependencies]
autopep8 = "^1.6"
coverage = "^6.2"
django-debug-toolbar = "^3.2"
django-extensions = "^3.1"
django-pdb = "^0.6"
dpytest = "^0.5"
flake8 = "^4.0"
freezegun = "^1.1"
ipdb = "^0.13"
isort = "^5.10"
model_bakery = "^1.3"
pytest = "^6.2"
pytest-asyncio = "^0.16"
pytest-django = "^4.4"
pytest-mock = "^3.6"
pytest-xdist = "^2.4"
Sphinx = "^4.3"
sphinx-rtd-theme = "^1.0"
werkzeug = "^2.0"

[build-system]
requires = ["poetry>=1.1"]
build-backend = "poetry.masonry.api"
