[tool.poetry]
name = "oil-and-rope"
version = "0.0.2"
description = "Oil & Rope is a Django project for managing Roleplay Games."
authors = ["LeCuay <suso.becerra98@gmail.com>"]
license = "MIT"
repository = "https://github.com/oil-rope/oil-and-rope/"

[tool.poetry.dependencies]
python = "3.9.5"
Django = "3.2.5"
channels = "^3.0"
channels-redis = "^3.3.0"
"discord.py" = {extras = ["voice"], version = "^1.7"}
django-crispy-forms = "^1.11"
django-ckeditor = "^6.1"
django-cors-headers = "^3.7"
django-modeltranslation = "^0.17"
django-mptt = "^0.12"
django-mptt-admin = "^2.1"
djangorestframework = "^3.12"
django-simple-history = "^3.0"
django-tables2 = "^2.4"
faker = "^8.6"
gunicorn = "^20.1"
Pillow = "^9.0"
psycopg2 = "^2.8"
python-dateutil = "^2.8"
python-dotenv = "^0.19"
requests = "^2.24"
Twisted = {extras = ["tls", "http2"], version = "^21.2"}
xlrd = "^2.0"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5"
coverage = "^5.5"
django-extensions = "^3.1"
django-pdb = "^0.6"
flake8 = "^3.9"
freezegun = "^1.1"
ipdb = "^0.13"
isort = "^5.8"
model_bakery = "^1.3"
pytest = "^6.2"
pytest-asyncio = "^0.15"
pytest-django = "^4.4"
pytest-xdist = "^2.2"
werkzeug = "^2.0"
dpytest = "^0.5.3"
pytest-mock = "^3.6.1"

[build-system]
requires = ["poetry>=1.1"]
build-backend = "poetry.masonry.api"
