[tool.poetry]
name = "oil-and-rope"
version = "0.0.1"
description = "Oil & Rope is a Django project for managing Roleplay Games."
authors = ["LeCuay <suso.becerra98@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
Django = "2.2.*"
channels = "^2.4.0"
"discord.py" = {extras = ["voice"], version = "^1.3.3"}
django-crispy-forms = "^1.9.1"
django-ckeditor = "^5.9.0"
django-modeltranslation = "^0.15"
django-mptt = "^0.11.0"
django-mptt-admin = "^1.0.1"
django-simple-history = "^2.10.0"
django-tables2 = "^2.3.1"
djangorestframework = "^3.11.0"
faker = "^4.1.0"
gunicorn = "^20.0.4"
Pillow = "^7.1.2"
psycopg2-binary = "^2.8.5"
python-dateutil = "^2.8.1"
python-dotenv = "^0.13.0"
Twisted = {extras = ["tls", "http2"], version = "^20.3.0"}
xlrd = "^1.2.0"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.2"
channels_redis = "^2.4.2"
django-extensions = "^2.2.9"
django-pdb = "^0.6.2"
flake8 = "^3.8.2"
freezegun = "^0.3.15"
ipdb = "^0.13.2"
isort = "^4.3.21"
model_bakery = "^1.1.0"
pytest = "^5.4.2"
pytest-asyncio = "^0.12.0"
pytest-cov = "^2.9.0"
pytest-django = "^3.9.0"
pytest-mock = "^3.1.0"
pytest-xdist = "^1.32.0"
selenium = "^3.141.0"
werkzeug = "^1.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
