[tool.poetry]
name = "oil-and-rope"
version = "0.0.2"
description = "Oil & Rope is a Django project for managing Roleplay Games."
authors = ["LeCuay <suso.becerra98@gmail.com>"]
license = "MIT"
repository = "https://github.com/oil-rope/oil-and-rope/"

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3"
channels = "^2"
"discord.py" = {extras = ["voice"], version = "^1"}
django-crispy-forms = "^1"
django-ckeditor = "^5"
django-modeltranslation = "^0"
django-mptt = "^0"
django-mptt-admin = "^1"
django-simple-history = "^2"
django-tables2 = "^2"
djangorestframework = "^3"
faker = "^4"
gunicorn = "^20"
Pillow = "^7"
psycopg2-binary = "^2"
python-dateutil = "^2"
python-dotenv = "^0"
requests = "^2.24.0"
Twisted = {extras = ["tls", "http2"], version = "^20"}
xlrd = "^1"

[tool.poetry.dev-dependencies]
autopep8 = "^1"
channels_redis = "^2"
django-extensions = "^2"
django-pdb = "^0"
flake8 = "^3"
freezegun = "^0"
ipdb = "^0"
isort = "^5"
model_bakery = "^1"
pytest = "^5"
pytest-asyncio = "^0"
pytest-cov = "^2"
pytest-django = "^3"
pytest-env = "^0.6.2"
pytest-mock = "^3"
pytest-xdist = "^1"
selenium = "^3"
werkzeug = "^1"
django-debug-toolbar = "^2.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
