# Generated by Django 4.0 on 2022-02-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='entry_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='entry created at'),
        ),
        migrations.AlterField(
            model_name='track',
            name='entry_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='entry updated at'),
        ),
    ]
