# Generated by Django 4.0.2 on 2022-02-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_track_entry_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
            preserve_default=False,
        ),
    ]
