# Generated by Django 4.0.2 on 2022-02-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_track_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False, verbose_name='identifier'),
        ),
    ]
