# Generated by Django 4.1 on 2022-11-16 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('common', '0005_vote_vote_common_vote_user_id_dea87d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label__in': ('roleplay',), 'model__in': ('campaign', 'place')}, on_delete=django.db.models.deletion.CASCADE, related_name='vote_set', to='contenttypes.contenttype', verbose_name='model associated'),
        ),
    ]
