# Generated by Django 4.1 on 2022-11-16 18:45

import common.files.upload
import common.validators.files
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0006_alter_vote_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('entry_created_at', models.DateTimeField(auto_now_add=True, verbose_name='entry created at')),
                ('entry_updated_at', models.DateTimeField(auto_now=True, verbose_name='entry updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identifier')),
                ('image', models.ImageField(max_length=255, upload_to=common.files.upload.default_upload_to, validators=[common.validators.files.validate_file_size], verbose_name='image')),
                ('object_id', models.CharField(db_index=True, max_length=255, verbose_name='object identifier')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='contenttypes.contenttype', verbose_name='model associated')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'ordering': ['-entry_created_at', '-entry_updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['content_type', 'object_id'], name='common_imag_content_4fea9c_idx'),
        ),
    ]
