FROM python:3.9-slim

RUN apt-get update
RUN apt-get install -y gcc
RUN apt-get install -y libpq-dev
RUN apt-get install -y gettext
RUN apt-get install -y vim
RUN pip install poetry

WORKDIR /app/

# We first install in orde to cache
COPY ./pyproject.toml .
COPY ./poetry.lock .
RUN poetry install

COPY . /app/
COPY ./docker/docker-entrypoint.sh /usr/local/bin/

# In order to always have Gunicorn against 0.0.0.0:8000 we set the following environment variables
ENV GUNICORN_WSGI_MODULE="oilandrope.asgi" \
GUNICORN_WORKER_CLASS="uvicorn.workers.UvicornWorker" \
GUNICORN_DAEMON="False" \
GUNICORN_ACCESS_LOGFILE="-" \
GUNICORN_ERROR_LOGFILE="-" \
GUNICORN_SOCK="" \
GUNICORN_IP="0.0.0.0" \
GUNICORN_PORT="8000" \
DJANGO_SETTINGS_MODULE="oilandrope.dev_settings" \
DEBUG="True" \
DEBUG_TEMPLATE="True"

ENTRYPOINT [ "docker-entrypoint.sh" ]

EXPOSE 8000
