# Generated by Django 3.2.5 on 2021-07-01 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roleplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinsession',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_in_session_set', to=settings.AUTH_USER_MODEL, verbose_name='player'),
        ),
        migrations.AlterField(
            model_name='playerinsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_in_session_set', to='roleplay.session', verbose_name='session'),
        ),
    ]
