# Generated by Django 3.2.4 on 2021-06-30 16:11

import common.files.upload
import common.validators.files
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20210622_1301'),
        ('roleplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['name', '-entry_created_at', '-entry_updated_at'], 'verbose_name': 'domain', 'verbose_name_plural': 'domains'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name', '-entry_created_at', '-entry_updated_at'], 'verbose_name': 'place', 'verbose_name_plural': 'places'},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['-entry_created_at', 'name'], 'verbose_name': 'race', 'verbose_name_plural': 'races'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-entry_created_at', 'name'], 'verbose_name': 'session', 'verbose_name_plural': 'sessions'},
        ),
        migrations.AlterField(
            model_name='domain',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'domain'), (1, 'subdomain')], default=0, verbose_name='domain type'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=common.files.upload.default_upload_to, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=25, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=common.files.upload.default_upload_to, validators=[common.validators.files.validate_file_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places_owned', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='place',
            name='parent_site',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_sites', to='roleplay.place', verbose_name='parent site'),
        ),
        migrations.AlterField(
            model_name='place',
            name='site_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'house'), (1, 'town'), (2, 'village'), (3, 'city'), (4, 'metropolis'), (5, 'forest'), (6, 'hills'), (7, 'mountains'), (8, 'mines'), (9, 'river'), (10, 'sea'), (11, 'desert'), (12, 'tundra'), (13, 'unusual'), (14, 'island'), (15, 'country'), (16, 'continent'), (17, 'world'), (18, 'ocean')], default=1, verbose_name='site type'),
        ),
        migrations.AlterField(
            model_name='place',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='race',
            name='affected_by_armor',
            field=models.BooleanField(default=True, help_text='declares if this race is affected by armor penalties', verbose_name='affected by armor'),
        ),
        migrations.AlterField(
            model_name='race',
            name='charisma',
            field=models.SmallIntegerField(default=0, verbose_name='charisma'),
        ),
        migrations.AlterField(
            model_name='race',
            name='constitution',
            field=models.SmallIntegerField(default=0, verbose_name='constitution'),
        ),
        migrations.AlterField(
            model_name='race',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='race',
            name='dexterity',
            field=models.SmallIntegerField(default=0, verbose_name='dexterity'),
        ),
        migrations.AlterField(
            model_name='race',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=common.files.upload.default_upload_to, validators=[common.validators.files.validate_file_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='race',
            name='intelligence',
            field=models.SmallIntegerField(default=0, verbose_name='intelligence'),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='race',
            name='strength',
            field=models.SmallIntegerField(default=0, verbose_name='strength'),
        ),
        migrations.AlterField(
            model_name='race',
            name='users',
            field=models.ManyToManyField(db_index=True, related_name='race_set', through='roleplay.RaceUser', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.AlterField(
            model_name='race',
            name='wisdom',
            field=models.SmallIntegerField(default=0, verbose_name='wisdom'),
        ),
        migrations.AlterField(
            model_name='raceuser',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='ownership'),
        ),
        migrations.AlterField(
            model_name='raceuser',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m2m_race_set', to='roleplay.race', verbose_name='race'),
        ),
        migrations.AlterField(
            model_name='raceuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m2m_race_set', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='session',
            name='chat',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_set', related_query_name='session', to='chat.chat', verbose_name='chat'),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='session',
            name='game_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm_session_set', related_query_name='gm_session', to=settings.AUTH_USER_MODEL, verbose_name='game master'),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='session',
            name='next_game',
            field=models.DateTimeField(blank=True, null=True, verbose_name='next session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='players',
            field=models.ManyToManyField(related_name='session_set', related_query_name='session', to=settings.AUTH_USER_MODEL, verbose_name='players'),
        ),
        migrations.AlterField(
            model_name='session',
            name='system',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pathfinder')], verbose_name='system'),
        ),
        migrations.AlterField(
            model_name='session',
            name='world',
            field=models.ForeignKey(limit_choices_to={'site_type': 17}, on_delete=django.db.models.deletion.CASCADE, related_name='session_set', related_query_name='session', to='roleplay.place', verbose_name='world'),
        ),
    ]
