# Generated by Django 4.0 on 2022-02-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='entry_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='entry created at'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='entry_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='entry updated at'),
        ),
        migrations.AlterField(
            model_name='place',
            name='entry_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='entry created at'),
        ),
        migrations.AlterField(
            model_name='place',
            name='entry_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='entry updated at'),
        ),
        migrations.AlterField(
            model_name='playerinsession',
            name='entry_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='entry created at'),
        ),
        migrations.AlterField(
            model_name='playerinsession',
            name='entry_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='entry updated at'),
        ),
        migrations.AlterField(
            model_name='playerinsession',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='race',
            name='entry_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='entry created at'),
        ),
        migrations.AlterField(
            model_name='race',
            name='entry_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='entry updated at'),
        ),
        migrations.AlterField(
            model_name='raceuser',
            name='entry_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='entry created at'),
        ),
        migrations.AlterField(
            model_name='raceuser',
            name='entry_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='entry updated at'),
        ),
        migrations.AlterField(
            model_name='session',
            name='entry_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='entry created at'),
        ),
        migrations.AlterField(
            model_name='session',
            name='entry_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='entry updated at'),
        ),
        migrations.AlterField(
            model_name='session',
            name='system',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pathfinder'), (1, 'Dungeons & Dragons')], verbose_name='system'),
        ),
    ]
