# Generated by Django 2.2.12 on 2020-05-04 09:05

import common.files.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0002_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=common.files.upload.default_upload_to, verbose_name='Image'),
        ),
    ]
