# Generated by Django 2.2.12 on 2020-05-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0003_domain_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
