# Generated by Django 4.0.2 on 2022-02-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0003_alter_domain_description_alter_domain_domain_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinsession',
            name='id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False, verbose_name='identifier'),
        ),
    ]
