# Generated by Django 2.2.12 on 2020-06-05 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0005_auto_20200516_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places_owned', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
