# Generated by Django 4.0.3 on 2022-03-07 12:00

import common.files.upload
import common.validators.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0005_alter_place_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=common.files.upload.default_upload_to, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=common.files.upload.default_upload_to, validators=[common.validators.files.validate_file_size], verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='race',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=common.files.upload.default_upload_to, validators=[common.validators.files.validate_file_size], verbose_name='image'),
            preserve_default=False,
        ),
    ]
