# Generated by Django 4.0.3 on 2022-03-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0006_alter_domain_image_alter_place_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'domain'), (1, 'subdomain')], default=0, verbose_name='domain type'),
        ),
        migrations.AlterField(
            model_name='place',
            name='site_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'house'), (1, 'town'), (2, 'village'), (3, 'city'), (4, 'metropolis'), (5, 'forest'), (6, 'hills'), (7, 'mountains'), (8, 'mines'), (9, 'river'), (10, 'sea'), (11, 'desert'), (12, 'tundra'), (13, 'unusual'), (14, 'island'), (15, 'country'), (16, 'continent'), (17, 'world'), (18, 'ocean')], default=1, verbose_name='site type'),
        ),
    ]
