# Generated by Django 2.2.12 on 2020-06-07 11:31

import common.files.upload
import common.validators.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0006_auto_20200605_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=common.files.upload.default_upload_to, validators=[common.validators.files.validate_file_size], verbose_name='Image'),
        ),
    ]
