# Generated by Django 4.0.3 on 2022-03-28 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chat_discord_id'),
        ('roleplay', '0006_alter_domain_image_alter_place_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerinsession',
            options={'verbose_name': 'player in session', 'verbose_name_plural': 'players in session'},
        ),
        migrations.RemoveField(
            model_name='session',
            name='description',
        ),
        migrations.AddField(
            model_name='session',
            name='plot',
            field=models.TextField(blank=True, verbose_name='plot'),
        ),
        migrations.AlterField(
            model_name='session',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', related_query_name='session', to='chat.chat', verbose_name='chat'),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='identifier'),
        ),
    ]
