# Generated by Django 4.0.3 on 2022-03-30 22:52

import common.files.upload
import common.validators.files
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chat_discord_id'),
        ('roleplay', '0006_alter_domain_image_alter_place_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerinsession',
            options={'verbose_name': 'player in session', 'verbose_name_plural': 'players in session'},
        ),
        migrations.RemoveField(
            model_name='session',
            name='description',
        ),
        migrations.AddField(
            model_name='session',
            name='image',
            field=models.ImageField(blank=True, upload_to=common.files.upload.default_upload_to, validators=[common.validators.files.validate_file_size], verbose_name='image'),
        ),
        migrations.AddField(
            model_name='session',
            name='plot',
            field=models.TextField(blank=True, verbose_name='plot'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'domain'), (1, 'subdomain')], default=0, verbose_name='domain type'),
        ),
        migrations.AlterField(
            model_name='place',
            name='site_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'house'), (1, 'town'), (2, 'village'), (3, 'city'), (4, 'metropolis'), (5, 'forest'), (6, 'hills'), (7, 'mountains'), (8, 'mines'), (9, 'river'), (10, 'sea'), (11, 'desert'), (12, 'tundra'), (13, 'unusual'), (14, 'island'), (15, 'country'), (16, 'continent'), (17, 'world'), (18, 'ocean')], default=1, verbose_name='site type'),
        ),
        migrations.AlterField(
            model_name='session',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', related_query_name='session', to='chat.chat', verbose_name='chat'),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='identifier'),
        ),
    ]
