# Generated by Django 4.0.3 on 2022-04-29 10:36

import common.files.upload
import common.validators.files
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0008_create_bot_user'),
        ('chat', '0007_alter_chat_name'),
        ('roleplay', '0007_alter_playerinsession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('entry_created_at', models.DateTimeField(auto_now_add=True, verbose_name='entry created at')),
                ('entry_updated_at', models.DateTimeField(auto_now=True, verbose_name='entry updated at')),
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, verbose_name='identifier')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('resume', models.CharField(blank=True, max_length=254, verbose_name='resume')),
                ('system', models.PositiveSmallIntegerField(choices=[(0, 'Pathfinder 1e'), (1, 'Dungeons & Dragons 3.5')], verbose_name='system')),
                ('cover_image', models.ImageField(blank=True, upload_to=common.files.upload.default_upload_to, validators=[common.validators.files.validate_file_size], verbose_name='cover image')),
                ('is_public', models.BooleanField(default=False, verbose_name='public')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('discord_channel_id', models.CharField(blank=True, max_length=254, verbose_name='identifier for discord channel')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_set', to='chat.chat', verbose_name='chat')),
                ('place', models.ForeignKey(limit_choices_to={'site_type': 17}, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_set', to='roleplay.place', verbose_name='world')),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
                'ordering': ['-entry_created_at', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='session',
            name='system',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pathfinder 1e'), (1, 'Dungeons & Dragons 3.5')], verbose_name='system'),
        ),
        migrations.CreateModel(
            name='PlayerInCampaign',
            fields=[
                ('entry_created_at', models.DateTimeField(auto_now_add=True, verbose_name='entry created at')),
                ('entry_updated_at', models.DateTimeField(auto_now=True, verbose_name='entry updated at')),
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, verbose_name='identifier')),
                ('is_game_master', models.BooleanField(default=False, verbose_name='game master')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_in_campaign_set', to='roleplay.campaign', verbose_name='campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_in_campaign_set', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'player in campaign',
                'verbose_name_plural': 'players in campaign',
                'ordering': ['-entry_created_at', 'user__username'],
                'unique_together': {('user', 'campaign')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='users',
            field=models.ManyToManyField(related_name='campaign_set', through='roleplay.PlayerInCampaign', to=settings.AUTH_USER_MODEL, verbose_name='players'),
        ),
    ]
