# Generated by Django 3.0.7 on 2020-06-20 09:52

import common.files.upload
import common.validators.files
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roleplay', '0007_auto_20200607_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Entry created at')),
                ('entry_updated_at', models.DateTimeField(auto_now=True, verbose_name='Entry updated at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('strength', models.SmallIntegerField(default=0, verbose_name='Strength')),
                ('dexterity', models.SmallIntegerField(default=0, verbose_name='Dexterity')),
                ('constitution', models.SmallIntegerField(default=0, verbose_name='Constitution')),
                ('intelligence', models.SmallIntegerField(default=0, verbose_name='Intelligence')),
                ('wisdom', models.SmallIntegerField(default=0, verbose_name='Wisdom')),
                ('charisma', models.SmallIntegerField(default=0, verbose_name='Charisma')),
                ('affected_by_armor', models.BooleanField(default=True, help_text='Declares if this race is affected by armor penalties', verbose_name='Affected by armor')),
                ('image', models.ImageField(blank=True, null=True, upload_to=common.files.upload.default_upload_to, validators=[common.validators.files.validate_file_size], verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Race',
                'verbose_name_plural': 'Races',
                'ordering': ['-entry_created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RaceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Entry created at')),
                ('entry_updated_at', models.DateTimeField(auto_now=True, verbose_name='Entry updated at')),
                ('is_owner', models.BooleanField(default=False, verbose_name='Ownership')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m2m_race_set', to='roleplay.Race', verbose_name='Race')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m2m_race_set', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-entry_created_at', 'entry_updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='race',
            name='users',
            field=models.ManyToManyField(db_index=True, related_name='race_set', through='roleplay.RaceUser', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
