# Generated by Django 4.0.3 on 2022-05-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0008_campaign_playerincampaign_remove_session_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='is_public',
            field=models.BooleanField(default=False, help_text='can this campaign be accessed by anyone?', verbose_name='public'),
        ),
    ]
