# Generated by Django 4.0.3 on 2022-05-06 08:29

import common.files.upload
import common.validators.files
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('roleplay', '0009_session_campaign_session_description_and_more'), ('roleplay', '0010_remove_session_chat_remove_session_players_and_more')]

    dependencies = [
        ('roleplay', '0008_campaign_alter_session_system_playerincampaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='session_set', to='roleplay.campaign', verbose_name='campaign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='session',
            name='image',
            field=models.ImageField(blank=True, upload_to=common.files.upload.default_upload_to, validators=[common.validators.files.validate_file_size], verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='session',
            name='plot',
            field=models.TextField(blank=True, help_text='one line resume', verbose_name='plot'),
        ),
        migrations.RemoveField(
            model_name='session',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='session',
            name='players',
        ),
        migrations.RemoveField(
            model_name='session',
            name='world',
        ),
        migrations.DeleteModel(
            name='PlayerInSession',
        ),
    ]
