# Generated by Django 3.1.1 on 2020-09-25 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200919_1238'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roleplay', '0008_auto_20200620_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Entry created at')),
                ('entry_updated_at', models.DateTimeField(auto_now=True, verbose_name='Entry updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('next_game', models.DateTimeField(blank=True, null=True, verbose_name='Next session')),
                ('system', models.PositiveSmallIntegerField(choices=[(0, 'Pathfinder')], verbose_name='System')),
                ('chat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_set', related_query_name='session', to='chat.chat', verbose_name='Chat')),
                ('game_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm_session_set', related_query_name='gm_session', to=settings.AUTH_USER_MODEL, verbose_name='GameMaster')),
                ('players', models.ManyToManyField(related_name='session_set', related_query_name='session', to=settings.AUTH_USER_MODEL, verbose_name='Players')),
                ('world', models.ForeignKey(limit_choices_to={'site_type': 17}, on_delete=django.db.models.deletion.CASCADE, related_name='session_set', related_query_name='session', to='roleplay.place', verbose_name='World')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-entry_created_at', 'name'],
            },
        ),
    ]
