# Generated by Django 4.0.4 on 2022-06-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0008_campaign_playerincampaign_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='public'),
        ),
    ]
