# Generated by Django 3.0.8 on 2020-07-19 12:40

import common.files.upload
import common.validators.files
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roleplay', '0008_auto_20200620_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Entry created at')),
                ('entry_updated_at', models.DateTimeField(auto_now=True, verbose_name='Entry updated at')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('file', models.FileField(upload_to=common.files.upload.default_upload_to, validators=[common.validators.files.validate_file_size, common.validators.files.validate_music_file], verbose_name='File')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='Identifier')),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'roleplay'), ('model__in', ['race', 'place'])), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Asociación')),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Music',
                'ordering': ['title', '-entry_created_at'],
            },
        ),
        migrations.CreateModel(
            name='MusicUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Entry created at')),
                ('entry_updated_at', models.DateTimeField(auto_now=True, verbose_name='Entry updated at')),
                ('is_owner', models.BooleanField(default=False, verbose_name='Ownership')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m2m_music_set', to='roleplay.Music', verbose_name='Music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m2m_music_set', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-entry_created_at', 'entry_updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='music',
            name='users',
            field=models.ManyToManyField(db_index=True, related_name='music_set', through='roleplay.MusicUser', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
