# Generated by Django 4.0.3 on 2022-05-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('roleplay', '0009_alter_place_site_type'), ('roleplay', '0010_alter_session_plot'), ('roleplay', '0011_session_gm_info')]

    dependencies = [
        ('roleplay', '0008_campaign_playerincampaign_remove_session_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='site_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'house'), (1, 'town'), (2, 'village'), (3, 'city'), (4, 'metropolis'), (5, 'forest'), (6, 'hills'), (7, 'mountains'), (8, 'mines'), (9, 'river'), (10, 'sea'), (11, 'desert'), (12, 'tundra'), (13, 'unusual'), (14, 'island'), (15, 'country'), (16, 'continent'), (17, 'world'), (18, 'ocean'), (19, 'temple'), (20, 'ruins')], default=1, verbose_name='site type'),
        ),
        migrations.AlterField(
            model_name='session',
            name='plot',
            field=models.CharField(blank=True, help_text='one line resume.', max_length=254, verbose_name='plot'),
        ),
        migrations.AddField(
            model_name='session',
            name='gm_info',
            field=models.TextField(blank=True, help_text='information specific to the game master.', verbose_name='game master info'),
        ),
    ]
