# Generated by Django 4.0.4 on 2022-05-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0009_alter_campaign_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-next_game', 'name', '-entry_updated_at'], 'verbose_name': 'session', 'verbose_name_plural': 'sessions'},
        ),
        migrations.RemoveField(
            model_name='session',
            name='system',
        ),
    ]
