# Generated by Django 4.1 on 2022-11-16 19:23

import django.apps.registry
import django.db.backends.base.schema
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_default_for_owner_forward(
    apps: django.apps.registry.Apps,
    schema_editor: django.db.backends.base.schema.BaseDatabaseSchemaEditor,
):
    User = apps.get_model('registration', 'User')
    Race = apps.get_model('roleplay', 'Race')

    oilandrope_bot = User.objects.get(email='oilandropeteam@gmail.com')
    race_without_owners = Race.objects.filter(owner__isnull=True)

    for race in race_without_owners:
        race.owner_id = oilandrope_bot.id
    Race.objects.bulk_update(objs=race_without_owners, fields=['owner_id'])


def set_default_for_owner_reverse(
    apps: django.apps.registry.Apps,
    schema_editor: django.db.backends.base.schema.BaseDatabaseSchemaEditor,
):
    # No reverse function needed
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roleplay', '0011_remove_place_user_alter_place_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='image',
        ),
        migrations.RemoveField(
            model_name='race',
            name='users',
        ),
        migrations.AddField(
            model_name='race',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_set', to='roleplay.campaign', verbose_name='campaign'),
        ),
        migrations.AddField(
            model_name='race',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_set', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.RunPython(code=set_default_for_owner_forward, reverse_code=set_default_for_owner_reverse),
        migrations.AlterField(
            model_name='race',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_set', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='race',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_set', to='roleplay.place', verbose_name='place'),
        ),
        migrations.AlterField(
            model_name='race',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='identifier'),
        ),
        migrations.DeleteModel(
            name='RaceUser',
        ),
    ]
