# Generated by Django 4.1.2 on 2022-11-21 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roleplay', '0012_remove_race_image_remove_race_users_race_campaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_created_at', models.DateTimeField(auto_now_add=True, verbose_name='entry created at')),
                ('entry_updated_at', models.DateTimeField(auto_now=True, verbose_name='entry updated at')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_es', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='description')),
                ('system', models.SmallIntegerField(choices=[(0, 'Pathfinder 1e'), (1, 'Dungeons & Dragons 3.5')], db_index=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'type of trait',
                'verbose_name_plural': 'types of trait',
                'ordering': ['-entry_created_at', 'name', '-entry_updated_at'],
                'unique_together': {('name', 'system')},
            },
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('entry_created_at', models.DateTimeField(auto_now_add=True, verbose_name='entry created at')),
                ('entry_updated_at', models.DateTimeField(auto_now=True, verbose_name='entry updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identifier')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('object_id', models.CharField(db_index=True, max_length=255, verbose_name='object identifier')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_set', to='contenttypes.contenttype', verbose_name='model associated')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_set', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_set', to='roleplay.traittype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'trait',
                'verbose_name_plural': 'traits',
                'ordering': ['-entry_created_at', 'name', '-entry_updated_at'],
            },
        ),
        migrations.AddField(
            model_name='trait',
            name='source',
            field=models.CharField(blank=True, help_text='where does this information come from?', max_length=255, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='trait',
            name='source_link',
            field=models.URLField(blank=True, help_text='link to the source information', verbose_name='source link'),
        ),
    ]
