# Generated by Django 4.1.2 on 2022-11-21 16:00

import django.apps.registry
import django.db.backends.base.schema
from django.db import migrations

import roleplay.enums


def populate_initial_trait_types_forward(
    apps: django.apps.registry.Apps,
    schema_editor: django.db.backends.base.schema.BaseDatabaseSchemaEditor,
):
    TraitType = apps.get_model('roleplay', 'TraitType')
    # NOTE: All these traits have been retrieved from Pathfinder's Official Website (https://aonprd.com/Traits.aspx)
    trait_types = [
        TraitType(name='Basic (Combat)', name_en='Basic (Combat)', name_es='Básicos (Combate)', system=roleplay.enums.RoleplaySystems.PATHFINDER_1),
        TraitType(name='Basic (Faith)', name_en='Basic (Faith)', name_es='Básicos (Fé)', system=roleplay.enums.RoleplaySystems.PATHFINDER_1),
        TraitType(name='Basic (Magic)', name_en='Basic (Magic)', name_es='Básicos (Magia)', system=roleplay.enums.RoleplaySystems.PATHFINDER_1),
        TraitType(name='Basic (Social)', name_en='Basic (Social)', name_es='Básicos (Social)', system=roleplay.enums.RoleplaySystems.PATHFINDER_1),
        TraitType(name='Campaign ', name_en='Campaign ', name_es='Campaña', system=roleplay.enums.RoleplaySystems.PATHFINDER_1),
        TraitType(name='Cosmic', name_en='Cosmic', name_es='Cósmico', system=roleplay.enums.RoleplaySystems.PATHFINDER_1),
        TraitType(name='Equipment', name_en='Equipment', name_es='Equipamiento', system=roleplay.enums.RoleplaySystems.PATHFINDER_1),
        TraitType(name='Exemplar', name_en='Exemplar', name_es='Ejemplar', system=roleplay.enums.RoleplaySystems.PATHFINDER_1),
        TraitType(name='Faction', name_en='Faction', name_es='Facción', system=roleplay.enums.RoleplaySystems.PATHFINDER_1),
        TraitType(name='Family', name_en='Family', name_es='Familia', system=roleplay.enums.RoleplaySystems.PATHFINDER_1),
        TraitType(name='Mount', name_en='Mount', name_es='Montura', system=roleplay.enums.RoleplaySystems.PATHFINDER_1),
        TraitType(name='Race', name_en='Race', name_es='Raza', system=roleplay.enums.RoleplaySystems.PATHFINDER_1),
        TraitType(name='Region', name_en='Region', name_es='Región', system=roleplay.enums.RoleplaySystems.PATHFINDER_1),
        TraitType(name='Religion', name_en='Religion', name_es='Religión', system=roleplay.enums.RoleplaySystems.PATHFINDER_1),
    ]
    # Bulk create in this context seems to not work properly for some reason
    TraitType.objects.bulk_create(objs=trait_types)


def populate_initial_trait_types_reverse(
    apps: django.apps.registry.Apps,
    schema_editor: django.db.backends.base.schema.BaseDatabaseSchemaEditor,
):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0013_traittype_trait'),
    ]

    operations = [
        migrations.RunPython(code=populate_initial_trait_types_forward, reverse_code=populate_initial_trait_types_reverse),
    ]
