# Generated by Django 2.2.12 on 2020-04-29 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': 'chat Message', 'verbose_name_plural': 'chat Messages'},
        ),
    ]
