# Generated by Django 4.0.2 on 2022-02-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_entry_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='identifier'),
        ),
    ]
