# Generated by Django 4.0.2 on 2022-03-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_id_alter_chatmessage_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
