# Generated by Django 3.0.8 on 2020-09-19 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200919_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='created_at',
            new_name='entry_created_at',
        ),
        migrations.AddField(
            model_name='chat',
            name='entry_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Entry created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='entry_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Entry updated at'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='entry_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Entry updated at'),
        ),
    ]
