# Generated by Django 4.0.3 on 2022-03-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='discord_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='discord identifier'),
        ),
    ]
