# Generated by Django 2.2.2 on 2019-12-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmenu',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='dynamicmenu',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='dynamicmenu',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='dynamicmenu',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
    ]
