# Generated by Django 2.2.2 on 2019-12-11 08:17

from django.db import migrations, models
import dynamic_menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_menu', '0002_auto_20191211_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicmenu',
            name='icon',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=dynamic_menu.models.dynamic_menu_path, verbose_name='Icon'),
        ),
    ]
