# Generated by Django 3.2.4 on 2021-06-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='premium user'),
        ),
    ]
