# Generated by Django 4.0.2 on 2022-02-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_profile_entry_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='alias'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='web',
            field=models.URLField(blank=True, default='', verbose_name='website'),
            preserve_default=False,
        ),
    ]
