# Generated by Django 4.0.3 on 2022-03-10 08:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('registration', '0005_alter_profile_bio_alter_profile_language'), ('registration', '0006_remove_profile_alias'), ('registration', '0007_alter_profile_bio')]

    dependencies = [
        ('registration', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='biography'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'english'), ('es', 'spanish')], default='en', max_length=10, verbose_name='language'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='alias',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='biography'),
        ),
    ]
