# Generated by Django 4.0.3 on 2022-03-09 09:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='biography'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'english'), ('es', 'spanish')], default='en', max_length=10, verbose_name='language'),
        ),
    ]
