# Generated by Django 4.0.3 on 2022-03-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_profile_bio_alter_profile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='alias',
        ),
    ]
