# Generated by Django 4.0.3 on 2022-03-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_profile_bio_alter_profile_language_squashed_0007_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='discord identifier'),
        ),
    ]
