# Generated by Django 3.1.1 on 2020-09-29 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordServer',
            fields=[
                ('entry_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Entry created at')),
                ('entry_updated_at', models.DateTimeField(auto_now=True, verbose_name='Entry updated at')),
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='Identifier')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('region', models.CharField(max_length=20, verbose_name='Region')),
                ('icon_url', models.URLField(blank=True, max_length=254, null=True, verbose_name='Icon URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('member_count', models.PositiveSmallIntegerField(default=0, verbose_name='Member count')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Discord Server',
                'verbose_name_plural': 'Discord Servers',
                'ordering': ['name', '-created_at', '-entry_updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscordTextChannel',
            fields=[
                ('entry_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Entry created at')),
                ('entry_updated_at', models.DateTimeField(auto_now=True, verbose_name='Entry updated at')),
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='Identifier')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Position')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('nsfw', models.BooleanField(blank=True, default=False, verbose_name='NSFW')),
                ('topic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Topic')),
                ('news', models.BooleanField(blank=True, default=False, verbose_name='News')),
            ],
            options={
                'verbose_name': 'Discord Text Channel',
                'verbose_name_plural': 'Discord Text Channels',
                'ordering': ['name', '-created_at', '-entry_updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('entry_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Entry created at')),
                ('entry_updated_at', models.DateTimeField(auto_now=True, verbose_name='Entry updated at')),
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='Identifier')),
                ('nick', models.CharField(max_length=50, verbose_name='Nick')),
                ('code', models.PositiveSmallIntegerField(verbose_name='Code')),
                ('avatar_url', models.URLField(blank=True, max_length=254, null=True, verbose_name='Avatar URL')),
                ('locale', models.CharField(blank=True, max_length=10, null=True, verbose_name='Locale')),
                ('premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Discord User',
                'verbose_name_plural': 'Discord Users',
                'ordering': ['nick', '-created_at', '-entry_updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscordVoiceChannel',
            fields=[
                ('entry_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Entry created at')),
                ('entry_updated_at', models.DateTimeField(auto_now=True, verbose_name='Entry updated at')),
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='Identifier')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Position')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('bitrate', models.PositiveSmallIntegerField(verbose_name='Bitrate')),
                ('discord_users', models.ManyToManyField(related_name='discord_voice_channels', to='bot.DiscordUser', verbose_name='Discord Users')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discord_voice_channels', to='bot.discordserver', verbose_name='Discord Server')),
            ],
            options={
                'verbose_name': 'Discord Voice Channel',
                'verbose_name_plural': 'Discord Voice Channels',
                'ordering': ['name', '-created_at', '-entry_updated_at'],
            },
        ),
    ]
