# Generated by Django 3.2.4 on 2021-06-30 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0002_auto_20200929_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discordserver',
            options={'ordering': ['name', '-created_at', '-entry_updated_at'], 'verbose_name': 'discord server', 'verbose_name_plural': 'discord servers'},
        ),
        migrations.AlterModelOptions(
            name='discordtextchannel',
            options={'ordering': ['name', '-created_at', '-entry_updated_at'], 'verbose_name': 'discord text channel', 'verbose_name_plural': 'discord text channels'},
        ),
        migrations.AlterModelOptions(
            name='discorduser',
            options={'ordering': ['nick', '-created_at', '-entry_updated_at'], 'verbose_name': 'discord user', 'verbose_name_plural': 'discord users'},
        ),
        migrations.AlterModelOptions(
            name='discordvoicechannel',
            options={'ordering': ['name', '-created_at', '-entry_updated_at'], 'verbose_name': 'discord voice channel', 'verbose_name_plural': 'discord voice channels'},
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='created_at',
            field=models.DateTimeField(verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='discord_users',
            field=models.ManyToManyField(related_name='discord_servers', to='bot.DiscordUser', verbose_name='discord users'),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='icon_url',
            field=models.URLField(blank=True, max_length=254, null=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='id',
            field=models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='member_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='member count'),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_servers', to='bot.discorduser', verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='region',
            field=models.CharField(max_length=20, verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='discordtextchannel',
            name='created_at',
            field=models.DateTimeField(verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='discordtextchannel',
            name='discord_users',
            field=models.ManyToManyField(related_name='discord_text_channels', to='bot.DiscordUser', verbose_name='discord users'),
        ),
        migrations.AlterField(
            model_name='discordtextchannel',
            name='id',
            field=models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='discordtextchannel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='discordtextchannel',
            name='news',
            field=models.BooleanField(blank=True, default=False, verbose_name='news'),
        ),
        migrations.AlterField(
            model_name='discordtextchannel',
            name='nsfw',
            field=models.BooleanField(blank=True, default=False, verbose_name='nsfw'),
        ),
        migrations.AlterField(
            model_name='discordtextchannel',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='discordtextchannel',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discord_text_channels', to='bot.discordserver', verbose_name='discord server'),
        ),
        migrations.AlterField(
            model_name='discordtextchannel',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='topic'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=254, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='code',
            field=models.PositiveSmallIntegerField(verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='created_at',
            field=models.DateTimeField(verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='id',
            field=models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='locale',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='locale'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='nick',
            field=models.CharField(max_length=50, verbose_name='nick'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='premium',
            field=models.BooleanField(default=False, verbose_name='premium'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='discordvoicechannel',
            name='bitrate',
            field=models.PositiveSmallIntegerField(verbose_name='bitrate'),
        ),
        migrations.AlterField(
            model_name='discordvoicechannel',
            name='created_at',
            field=models.DateTimeField(verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='discordvoicechannel',
            name='discord_users',
            field=models.ManyToManyField(db_index=True, related_name='discord_voice_channels', to='bot.DiscordUser', verbose_name='discord users'),
        ),
        migrations.AlterField(
            model_name='discordvoicechannel',
            name='id',
            field=models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='discordvoicechannel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='discordvoicechannel',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='discordvoicechannel',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discord_voice_channels', to='bot.discordserver', verbose_name='discord server'),
        ),
    ]
