# Generated by Django 3.2.5 on 2021-07-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20210630_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordtextchannel',
            name='discord_users',
        ),
        migrations.RemoveField(
            model_name='discordtextchannel',
            name='server',
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='discordvoicechannel',
            name='discord_users',
        ),
        migrations.RemoveField(
            model_name='discordvoicechannel',
            name='server',
        ),
        migrations.DeleteModel(
            name='DiscordServer',
        ),
        migrations.DeleteModel(
            name='DiscordTextChannel',
        ),
        migrations.DeleteModel(
            name='DiscordUser',
        ),
        migrations.DeleteModel(
            name='DiscordVoiceChannel',
        ),
    ]
