# Generated by Django 2.2.2 on 2019-12-08 15:23

from django.db import migrations, models
import django.db.models.deletion
import dynamic_menu.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Entry created at')),
                ('entry_updated_at', models.DateTimeField(auto_now=True, verbose_name='Entry updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('prepended_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prepended Text')),
                ('appended_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Appended Text')),
                ('url_resolver', models.CharField(blank=True, max_length=50, null=True, verbose_name='URL Resolver')),
                ('extra_urls_args', models.CharField(blank=True, max_length=254, null=True, verbose_name='Extra URL Parameters')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('staff_required', models.BooleanField(default=False, verbose_name='Staff Required')),
                ('superuser_required', models.BooleanField(default=False, verbose_name='SuperUser Required')),
                ('icon', models.FileField(max_length=254, upload_to=dynamic_menu.models.dynamic_menu_path, verbose_name='Icon')),
                ('menu_type', models.PositiveSmallIntegerField(choices=[(0, 'Standard Menu'), (1, 'Context Menu')], default=0, verbose_name='Menu Type')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='dynamic_menu.DynamicMenu')),
                ('permissions_required', models.ManyToManyField(blank=True, related_name='menus', to='auth.Permission', verbose_name='Permissions required')),
                ('related_model', models.ManyToManyField(blank=True, related_name='menus', to='contenttypes.ContentType', verbose_name='Related Model')),
            ],
            options={
                'verbose_name': 'Dynamic Menu',
                'verbose_name_plural': 'Dynamic Menus',
            },
        ),
    ]
