# Generated by Django 3.2.8 on 2021-11-05 12:11

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Entry created at')),
                ('entry_updated_at', models.DateTimeField(auto_now=True, verbose_name='Entry updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_en_us', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_es_ES', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en_us', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_es_ES', models.TextField(blank=True, null=True, verbose_name='description')),
                ('prepended_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='prepended text')),
                ('appended_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='appended text')),
                ('url_resolver', models.CharField(blank=True, max_length=50, null=True, verbose_name='resolver')),
                ('extra_urls_args', models.CharField(blank=True, max_length=254, null=True, verbose_name='extra parameters')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('staff_required', models.BooleanField(default=False, verbose_name='staff required')),
                ('menu_type', models.PositiveSmallIntegerField(choices=[(0, 'Standard menu'), (1, 'Context menu')], default=0, verbose_name='menu type')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='dynamic_menu.dynamicmenu', verbose_name='parent menu')),
                ('permissions_required', models.ManyToManyField(blank=True, related_name='menus', to='auth.Permission', verbose_name='permissions required')),
            ],
            options={
                'verbose_name': 'Dynamic Menu',
                'verbose_name_plural': 'Dynamic Menus',
            },
        ),
    ]
