# Generated by Django 3.2.8 on 2021-11-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicmenu',
            old_name='description_en_us',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='dynamicmenu',
            old_name='description_es_ES',
            new_name='description_es',
        ),
        migrations.RenameField(
            model_name='dynamicmenu',
            old_name='name_en_us',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='dynamicmenu',
            old_name='name_es_ES',
            new_name='name_es',
        ),
    ]
