# Generated by Django 4.0 on 2022-02-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_menu', '0002_auto_20211109_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicmenu',
            options={'verbose_name': 'dynamic menu', 'verbose_name_plural': 'dynamic menus'},
        ),
        migrations.AlterField(
            model_name='dynamicmenu',
            name='entry_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='entry created at'),
        ),
        migrations.AlterField(
            model_name='dynamicmenu',
            name='entry_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='entry updated at'),
        ),
        migrations.AlterField(
            model_name='dynamicmenu',
            name='menu_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Standard Menu'), (1, 'Context Menu')], default=0, verbose_name='menu type'),
        ),
    ]
