# Generated by Django 3.2.5 on 2021-07-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_menu', '0002_auto_20210630_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicmenu',
            old_name='description_en',
            new_name='description_en_us',
        ),
        migrations.RenameField(
            model_name='dynamicmenu',
            old_name='description_es',
            new_name='description_es_ES',
        ),
        migrations.RenameField(
            model_name='dynamicmenu',
            old_name='name_en',
            new_name='name_en_us',
        ),
        migrations.RenameField(
            model_name='dynamicmenu',
            old_name='name_es',
            new_name='name_es_ES',
        ),
    ]
