# Generated by Django 4.0.2 on 2022-02-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_menu', '0003_alter_dynamicmenu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicmenu',
            name='appended_text',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='appended text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dynamicmenu',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dynamicmenu',
            name='extra_urls_args',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='extra parameters'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dynamicmenu',
            name='prepended_text',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='prepended text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dynamicmenu',
            name='url_resolver',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='resolver'),
            preserve_default=False,
        ),
    ]
