# Generated by Django 4.0.3 on 2022-03-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_menu', '0004_alter_dynamicmenu_appended_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicmenu',
            name='menu_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'standard menu'), (1, 'context menu')], default=0, verbose_name='menu type'),
        ),
    ]
