name: (Dev) Django Checker

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*

jobs:
  python-build-without-postgres:
    name: Python Build
    runs-on: ubuntu-latest
    env:
      # NOTE: This is needed for coverage on HTML
      DEBUG_TEMPLATE: True
      DJANGO_SETTINGS_MODULE: oilandrope.dev_settings

    # Redis
    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install

      - name: Lint with flake8
        run: |
          poetry run flake8 --config=setup.cfg

      - name: Check iSort
        run: |
          poetry run isort . --check --diff

      - name: Pytest
        run: |
          cp .env.example .env
          poetry run ./manage.py test -- --cov-fail-under=96

      - name: Django Check
        run: |
          poetry run ./manage.py migrate
          poetry run ./manage.py check
