name: Oil & Rope CI

on:
  push

env:
  CONTEXT: ${{ contains(github.event.ref, 'tag') && 'prod' || github.ref_name == 'master' && 'prod' || 'dev' }}

jobs:
  testing-and-linter:
    name: Tests and Lint
    runs-on: ubuntu-latest
    env:
      # NOTE: This is needed for coverage on HTML
      DEBUG_TEMPLATE: True
      DJANGO_SETTINGS_MODULE: oilandrope.settings
      DB_USER: oilandrope
      DB_PASSWORD: p4ssw0rd@
      DB_NAME: oilandrope_db
      DB_HOST: localhost
      DB_PORT: 5432

    # Set up Postgres and Redis
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: oilandrope
          POSTGRES_PASSWORD: p4ssw0rd@
          POSTGRES_DB: oilandrope_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis
        ports:
          - 6379:6379

    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Poetry cache
        uses: actions/cache@v3
        id: cache-poetry
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install poetry
        run: |
          pip install poetry

      - name: Install dependencies
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: |
          poetry install

      - name: Lint with flake8
        run: |
          poetry run flake8 --config=setup.cfg

      - name: Check iSort
        run: |
          poetry run isort . --check --diff

      - name: Check translations
        run: |
          sudo apt-get install gettext
          poetry run ./manage.py makemessages -l es
          git diff --exit-code
          poetry run ./manage.py compilemessages -l es

      - name: Django Check
        run: |
          poetry run ./manage.py migrate
          poetry run ./manage.py check

      # Since `poetry run ./manage.py` does not cover all files (maybe because there are *pre-pytest* reached) we user
      # `coverage run` in order to get a full coverage (difference is almost 10%)
      - name: Pytest
        env:
          DJANGO_SETTINGS_MODULE: oilandrope.dev_settings
        # TODO: OAR-18 fix the `fail-under` to remove this bypass
        run: |
          poetry run coverage run ./manage.py test
          poetry run coverage report --skip-covered --fail-under=90
          poetry run coverage xml --fail-under=90

      - name: Update coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false # CI can continue without Codecov
          verbose: true

  build-and-push:
    name: Build Images and Push
    runs-on: ubuntu-latest
    needs: testing-and-linter

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Since the format `developmentType/Code` is invalid we need to replace it
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]${{ github.ref_name }}" | sed -e 's/\//-/g'
        id: extra_branch_name

      - name: Build & Push Image
        if: ${{ success() }}
        uses: docker/build-push-action@v3
        env:
          DOCKERFILE: docker/3.9/Dockerfile.${{ env.CONTEXT }}
          TAG: ${{ steps.extra_branch_name.outputs.branch }}
        with:
          context: .
          push: true
          tags: oilandrope/core:${{ env.TAG }}
          file: ${{ env.DOCKERFILE }}
          cache-from: type=registry,ref=oilandrope/core:${{ env.TAG }}
          cache-to: type=inline
