name: Feature Checker (Node)

on:
  push:
    branches:
      - feature/*

jobs:
  node-build:
    name: Node Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['10.x', '12.x', '14.x']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Check syntax
        run: npm run lint

      - name: Test
        run: npm test